builds:
  - binary: helm-annotate
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
  
archives:
  - files:
    - LICENSE.txt
    - README.md
    - plugin.yaml
